hooks_enabled = true

[model]
name = "openrouter/healer-alpha"

[[hooks]]
name = "test_before_tool"
trigger = "before_tool"
command = "python3 ./scripts/test_tool.py"
enabled = true

[[hooks]]
name = "test_before_agent"
trigger = "before_agent"
command = "python3 ./scripts/test_tool.py"
enabled = true

[mcp_servers.filesystem]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "D:/mine/SimhaCLI",
]
enabled = true

[mcp_servers.github]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]
enabled = false

[mcp_servers.postgres]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-postgres",
]
enabled = false

[mcp_servers.playwright]
command = "npx"
args = [
    "-y",
    "@executeautomation/playwright-mcp-server",
]
enabled = false
