hooks_enabled = true

[model]
name = "minimax-m2.5:cloud"

[[hooks]]
name = "test_before_tool"
trigger = "before_tool"
command = "python3 ./scripts/test_tool.py"
enabled = true

[[hooks]]
name = "test_before_agent"
trigger = "before_agent"
command = "python3 ./scripts/test_tool.py"
enabled = true

[mcp_servers.filesystem]
command = "npx"
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "D:/SimhaCLI",
]
enabled = true
