hooks_enabled = true


[model]
name = "mistralai/devstral-2512:free" # nvidia/nemotron-3-nano-30b-a3b:free #qwen/qwen3-coder:free

[[hooks]]
name="test_before_tool"
trigger="before_tool"
command="python3 ./scripts/test_tool.py"

[[hooks]]
name="test_before_agent"
trigger="before_agent"
command="python3 ./scripts/test_tool.py"

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "D:/SimhaCLI"]
